### ISSUE TITLE
Upgrade all dependencies

### ISSUE THREAD

**Issue by wagnerjt** [jannikbuschke/gatsby-antd-docs#8]
I believe everything is straight-forward except the `gatsby-mdx`. It appears it is now `gatsby-plugin-mdx`. See [this](https://github.com/wagnerjt/neo4j-apps/commit/804d1979df409b7e759dc63d3adf253e859f8e68) for package upgrade details.

**Comment by jannikbuschke** [comment]
I updated the deps, was not straight forward but I think everything works now.
